# Generated by Django 5.1.1 on 2024-10-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phonenumber', models.BigIntegerField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('confirmpassword', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('price', models.BigIntegerField(max_length=100)),
                ('date', models.DateField()),
                ('expiredate', models.DateField()),
                ('phonenumber', models.CharField(max_length=15)),
                ('delivery', models.CharField(max_length=100)),
                ('negotiable', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('HDD', models.CharField(max_length=100)),
                ('screensize', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
                ('sold', models.CharField(max_length=100)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronic.category')),
            ],
        ),
    ]
