# Generated by Django 5.1.1 on 2024-10-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phonenumber',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
